#.github/sync.yml
group:
  - files:
      - source: CountCSVLine.py
        dest:   CountCSVLine.py
      - source: .gitignore
        dest:   .gitignore
      - source: .github/workflows/sync-up.yml
        dest:   .github/workflows/sync-up.yml
      - source: .github/sync.yml
        dest:   .github/sync.yml
    repos: |
        ZhongZheng782/wenchiehlee.quickconnect.to-Container.Manager
        ZhongZheng782/Andy
        ZhongZheng782/wenchiehlee.quickconnect.to
        ZhongZheng782/GoPublic
  - files:
      - source: wenchiehlee.quickconnect.to-Container.Manager-docker.json
        dest:   wenchiehlee.quickconnect.to-Container.Manager-docker.json
    repos: |
        ZhongZheng782/GoPublic
        ZhongZheng782/wenchiehlee.quickconnect.to-Container.Manager